[group:mybooks]
programs=tornado,nginx,nodejs

[program:tornado]
command=gosu mybooks:mybooks python3 server.py --with-library=/data/books/library --port=8000 --host=127.0.0.1 --logging=debug --log-file-prefix=/data/log/mybooks.log
directory=/var/www/mybooks
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:nginx]
command = /usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=unexpected

[program:nodejs]
command=gosu mybooks:mybooks npm run start
directory=/var/www/mybooks/app
autorestart=true
redirect_stderr=true
stdout_logfile=/data/log/nodejs.log

